import React from "react";
const insightsData = {
 1: [
  {
    title: "💡 Top 3 Categories Dominate Overall Spend",
    description:
      "Dining ($2.4M), Retail ($1.8M), and Groceries ($1.5M) lead overall spend across all consumer categories.",
  },
  {
    title: "💡 Strong Lifestyle Engagement Signals",
    description:
      "Streaming ($915K) and Wellness ($914K) show strong lifestyle engagement with nearly identical spend levels.",
  },
  {
    title: "💡 Pharmacy Outperforms Healthcare Significantly",
    description:
      "Pharmacy spend ($609K) is double healthcare ($302K), showing preference for direct medication purchases.",
  },
  {
    title: "💡 Moderate Digital Activity Across Channels",
    description:
      "Tech ($328K) and Online Shopping ($308K) reflect moderate digital activity levels.",
  },
  {
    title: "💡 Low-Traction Areas Need Strategic Focus",
    description:
      "Education, Fitness, and Transportation hover around $290K–$300K with consistent but limited engagement.",
  },
],


2: [
  {
    title: "💡 Top Performer: Green Spending Week",
    description:
      "Green Spending Week leads at $73.1K, showing strong sustainability appeal across consumer segments.",
  },
  {
    title: "💡 Wellness Gains Momentum",
    description:
      "Healthy Living and Active Life Rewards show high traction in health-focused segments, driving engagement.",
  },
  {
    title: "💡 Travel Strength Confirmed",
    description:
      "Fly More Deals ($66K) confirms continued interest in mobility-linked benefits and travel rewards.",
  },
  {
    title: "💡 Youth Campaigns Deliver Results",
    description:
      "Student Saver and Exam Prep perform well, highlighting strong youth engagement and educational focus.",
  },
  {
    title: "💡 Consistent Returns from Core Segments",
    description:
      "Family Planner and Senior Health Plan show steady, reliable performance with sustained user loyalty.",
  },
],

  3: [
    {
      title: "💡 High Alignment Campaigns",
      description:
        "Travel Elite (89%) and Cashback Master (85%) exhibit strong user alignment, suggesting these offerings are well-targeted and should be prioritized in future promotions or expanded across wider segments.",
    },
    {
      title: "💡 Strong Mid-Tier Performers",
      description:
        "Campaigns like Student Achieve (79%), E-Shopper (75%), and Fuel Saver (72%) also show solid engagement potential. These can benefit from scaled outreach or A/B tested incentives to push them into top-tier performance.",
    },
    {
      title: "💡 Low Match Alerts",
      description:
        "Family Planner (56%) and Entertainment Buff (57%) have the weakest alignment, hinting at possible misalignment with user preferences or segmentation issues. These campaigns may require recalibrated targeting criteria or adjusted content.",
    },
    {
      title: "💡 Balanced Category Spread",
      description:
        "The campaigns represent diverse user interests (fuel, travel, wellness, fashion, shopping), showing good portfolio breadth. Maintaining this variety while fine-tuning performance could help increase total recommendation effectiveness.",
    },
    {
      title: "💡 Optimization Potential",
      description:
        "With most campaigns scoring above 60%, there is a strong foundation for optimization. Refining creatives and leveraging data-driven personalization could push mid-performers like Wellness Boost (68%) and Fashion Forward (60%) into higher match brackets.",
    },
  ],
};

const headings = {
  1: "🤖 Gen AI Insights on chart",
  2: "🤖 Gen AI Insights on chart",
  3: "🤖 Gen AI Insights on chart",
};

const subheadings = {
  1: " Here are 5 concise, point-wise analytics insights based on the spending chart to guide strategic decisions:",
  2: "Here are 5 point-wise analytical insights based on the revenue generated by each campaign, with recommendations to guide strategic adjustments:",
  3: "Here are 5 analytics-driven, point-wise insights based on the recommendation performance data (measured by user match percentage):",
};

const LLMDetails = ({ graphId }) => {
  const insights = insightsData[graphId] || [];
  const heading = headings[graphId] || "Gen AI Insights";
  const subheading = subheadings[graphId] || "";

  return (
  <div className="bg-[#f1f7f9] dark:bg-[#1d2041] p-6 h-full">
  <h2 className="text-xl font-bold mb-2 text-blue-600 dark:text-indigo-300">
    {heading}
  </h2>
  <p className="mb-4 text-gray-800 dark:text-gray-400">{subheading}</p>
  <ol className="list-decimal pl-5 space-y-3">
    {insights.map((insight, idx) => (
      <li key={idx}>
        <span className="font-semibold text-blue-600 dark:text-gray-100">
          {insight.title}:{" "}
        </span>
        <span className="text-gray-700 dark:text-gray-400">
          {insight.description}
        </span>
      </li>
    ))}
  </ol>
</div>

  );
};

export default LLMDetails;
